CREATE TABLE FoodInv.Inv(id BIGINT NOT NULL primary key auto_increment,
`Rate`	INTEGER,
`Upc`	VARCHAR(15) COMMENT 'len=15',
`Item`	VARCHAR(46) COMMENT 'len=46' NOT NULL,
`Want`	INTEGER,
`Have`	INTEGER,
`Old`	INTEGER,
`Total`	INTEGER,
`LowInvAdj`	INTEGER,
`GetAlacart`	INTEGER,
`Need`	INTEGER,
`Meal`	VARCHAR(2) COMMENT 'len=2' NOT NULL,
`Subbed`	INTEGER,
`Wanted`	INTEGER,
`Tossed`	INTEGER,
`AvgOrder`	REAL,
`Max`	INTEGER,
`AvgEaten`	REAL,
`Comment`	VARCHAR(50) COMMENT 'len=50');
